"""
Export service for ResumeForge.
Generates downloadable reports and optimized resumes.
"""

from typing import Dict, List
from datetime import datetime
import json


class ExportService:
    """Handle exporting analysis results and optimized resumes."""
    
    def export_analysis_report(
        self,
        parsed_resume: 'ParsedResume',
        score_breakdown: 'ScoreBreakdown',
        ats_results: Dict,
        job_match: Dict = None
    ) -> str:
        """
        Export comprehensive analysis as markdown report.
        """
        report = []
        
        # Header
        report.append("# Resume Analysis Report")
        report.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        report.append(f"**Analyzed by:** ResumeForge AI\n")
        report.append("---\n")
        
        # Executive Summary
        report.append("## Executive Summary\n")
        report.append(f"- **Total Skills:** {len(parsed_resume.skills)}")
        report.append(f"- **Work Experience:** {len(parsed_resume.experience)} positions")
        report.append(f"- **Education:** {len(parsed_resume.education)} entries")
        
        if ats_results:
            avg_ats = ats_results.get('average_compatibility', 0)
            report.append(f"- **Average ATS Compatibility:** {avg_ats}/100")
        
        if score_breakdown:
            report.append(f"- **Overall Score:** {score_breakdown.overall_score}/100\n")
        
        report.append("---\n")
        
        # Contact Information
        report.append("## Contact Information\n")
        contact = parsed_resume.contact_info
        if contact.get('email'):
            report.append(f"- **Email:** {contact['email']}")
        if contact.get('phone'):
            report.append(f"- **Phone:** {contact['phone']}")
        if contact.get('linkedin'):
            report.append(f"- **LinkedIn:** {contact['linkedin']}")
        if contact.get('github'):
            report.append(f"- **GitHub:** {contact['github']}")
        report.append("")
        
        # Skills Summary
        report.append("## Top Skills\n")
        top_skills = sorted(parsed_resume.skills, key=lambda x: x.confidence, reverse=True)[:20]
        for skill in top_skills:
            report.append(f"- **{skill.name}** ({skill.confidence:.0%})")
        report.append("")
        
        # Experience Summary
        report.append("## Work Experience\n")
        for i, exp in enumerate(parsed_resume.experience, 1):
            report.append(f"### {i}. {exp.title or 'Position'}")
            if exp.company:
                report.append(f"**Company:** {exp.company}")
            if exp.duration:
                report.append(f"**Duration:** {exp.duration}")
            if exp.skills_used:
                report.append(f"**Skills:** {', '.join(exp.skills_used[:8])}")
            report.append("")
        
        # ATS Compatibility
        if ats_results:
            report.append("## ATS Compatibility\n")
            report.append(f"**Overall Grade:** {ats_results.get('overall_grade', 'N/A')}\n")
            
            if 'individual_results' in ats_results:
                report.append("### Individual ATS Scores\n")
                for ats_name, data in ats_results['individual_results'].items():
                    report.append(f"- **{ats_name}:** {data['compatibility_score']}/100")
                report.append("")
        
        # Recommendations
        if score_breakdown and score_breakdown.weaknesses:
            report.append("## Recommendations\n")
            for i, weakness in enumerate(score_breakdown.weaknesses, 1):
                report.append(f"{i}. {weakness}")
            report.append("")
        
        # Footer
        report.append("---\n")
        report.append("*Report generated by ResumeForge - AI-Powered Resume Analysis*")
        
        return "\n".join(report)
    
    def export_skills_list(self, skills: List['Skill']) -> str:
        """Export skills as a formatted list."""
        output = ["# Skills List\n"]
        
        # Group by category
        from collections import defaultdict
        by_category = defaultdict(list)
        
        for skill in skills:
            category = skill.category or "other"
            by_category[category].append(skill)
        
        for category, skill_list in sorted(by_category.items()):
            category_name = category.replace("_", " ").title()
            output.append(f"## {category_name}\n")
            
            sorted_skills = sorted(skill_list, key=lambda x: x.confidence, reverse=True)
            for skill in sorted_skills:
                output.append(f"- {skill.name}")
            output.append("")
        
        return "\n".join(output)
    
    def export_json(self, parsed_resume: 'ParsedResume') -> str:
        """Export parsed resume as JSON."""
        data = {
            "contact_info": parsed_resume.contact_info,
            "skills": [
                {
                    "name": s.name,
                    "category": s.category,
                    "confidence": s.confidence
                }
                for s in parsed_resume.skills
            ],
            "experience": [
                {
                    "title": e.title,
                    "company": e.company,
                    "duration": e.duration,
                    "description": e.description,
                    "skills_used": e.skills_used
                }
                for e in parsed_resume.experience
            ],
            "education": [
                {
                    "degree": e.degree,
                    "institution": e.institution,
                    "year": e.year,
                    "gpa": e.gpa
                }
                for e in parsed_resume.education
            ],
            "metadata": {
                "total_skills": len(parsed_resume.skills),
                "total_experience": len(parsed_resume.experience),
                "total_education": len(parsed_resume.education),
                "character_count": len(parsed_resume.raw_text)
            }
        }
        
        return json.dumps(data, indent=2)